title: "0x41434f"
description: Software Engineer. Mental Health Worker. Building toward Computational Psychiatry.
baseurl: ""
url: "https://ovabor.github.io"
markdown: kramdown
theme: minima
permalink: /essays/:title/
header_pages:
  - index.md
  - projects.md

